using System;
using NUnit.Framework;
using Moq;
using System.Collections.Generic;

[TestFixture]
class ClassExample1Test
{
    private Mock<IDisposable> _disp;
    private Mock<ICloneable> _clon;
    private ClassExample1 _classExample1;
    [SetUp]
    public void SetUp()
    {
        var a = default(int);
        var str = default(string);
        _disp = new Mock<IDisposable>();
        _clon = new Mock<ICloneable>();
        _classExample1 = new ClassExample1(_disp.Object, _clon.Object, a, str);
    }

    [Test]
    public void Func1()
    {
        var j = default(int);
        var k = default(int);
        var actual = _classExample1.Func1(j, k);
        var expected = default(int);
        Assert.That(actual, Is.EqualTo(expected));
        Assert.Fail("autogenerated");
    }

    [Test]
    public void Func2()
    {
        _classExample1.Func2();
        Assert.Fail("autogenerated");
    }
}