using System;
using NUnit.Framework;
using Moq;
using System.Collections.Generic;

[TestFixture]
class ClassExample2Test
{
    private ClassExample2 _classExample2;
    [SetUp]
    public void SetUp()
    {
        _classExample2 = new ClassExample2();
    }

    [Test]
    public void Funс1()
    {
        _classExample2.Funс1();
        Assert.Fail("autogenerated");
    }

    [Test]
    public void Func2()
    {
        _classExample2.Func2();
        Assert.Fail("autogenerated");
    }
}